version: '3.4'

services:
  app:
    image: ruby:2.6
    environment:
      - GEM_HOME=/bundle
      - BUNDLE_PATH=/bundle
      - HISTFILE=/app/tmp/.bash_history
    working_dir: /app
    volumes:
      - ..:/app
      - bundle:/bundle

volumes:
  bundle:
