ignore:
 - "**/*/Readme.md"
hostname: https://docs.anycable.io
url_prefix: <%= ENV.fetch("VERSION_PREFIX", "edge") %>/rails

groups:
  - name: Rails integration
    tracking_id: rails

defaults:
  groups:
    - rails
  tags:
    - docs
    - <%= ENV.fetch("VERSION_TAG", "edge") %>

pages:
  - "./*.md"
