name: Build

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_FORCE_RUBY_PLATFORM: 1
      CI: true
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7"]
        gemfile: ["gemfiles/rails6.gemfile"]
        allow_failure: [false]
        include:
          - ruby: "3.0"
            gemfile: "gemfiles/rails6.gemfile"
            allow_failure: false
          - ruby: "2.7"
            gemfile: "gemfiles/railsmaster.gemfile"
            allow_failure: false
          - ruby: "2.6"
            gemfile: "gemfiles/rails60.gemfile"
            allow_failure: false
          - ruby: "2.6"
            gemfile: "gemfiles/rails51.gemfile"
            allow_failure: true
    steps:
    - uses: actions/checkout@v2
    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        bundler: 2.2.15
    - name: Run RSpec
      continue-on-error: ${{ matrix.allow_failure }}
      run: |
        bundle exec rake spec
    - name: Run compatibility specs
      continue-on-error: ${{ matrix.allow_failure }}
      run: |
        bundle exec rake spec:compatibility
