name: Build

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  rspec:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip tests]') }}
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_FORCE_RUBY_PLATFORM: 1
      CI: true
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    services:
      redis:
        image: redis:6.0-alpine
        ports: ["6379:6379"]
        options: --health-cmd="redis-cli ping" --health-interval 1s --health-timeout 3s --health-retries 30
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0"]
        gemfile: ["gemfiles/rails6.gemfile"]
        include:
          - ruby: "3.2"
            gemfile: "gemfiles/rails7.gemfile"
          - ruby: "2.7"
            gemfile: "gemfiles/rails6.gemfile"
          - ruby: "3.1"
            gemfile: "gemfiles/railsmaster.gemfile"
          - ruby: "2.7"
            gemfile: "gemfiles/rails60.gemfile"
    steps:
    - uses: actions/checkout@v2
    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run RSpec
      continue-on-error: ${{ matrix.allow_failure }}
      run: |
        bundle exec rake spec
    - name: Run compatibility specs
      continue-on-error: ${{ matrix.allow_failure }}
      run: |
        bundle exec rake spec:compatibility
    - name: Run conformance tests with Anyt
      env:
        BUNDLE_GEMFILE: "gemfiles/anyt.gemfile"
      run: |
        bundle install
        bundle exec anyt --self-check
